### ISSUE TITLE
Tailwind 2.0.2 fails to work

### ISSUE THREAD

**Issue by MatthewLHolden** [jneterer/angular-tailwindcss-app#1]
Firstly, thanks for the repo, I have been bashing my head against the wall trying to get Tailwind integrated into Angular. When using Tailwind 2.0.2, the following error occurs:

```
ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--14-3!./node_modules/sass-loader/dist/cjs.js??ref--14-4!./node_modules/postcss-loader/src??postcss!./src/styles.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: true is not a PostCSS plugin
    at Processor.normalize (/mypath/angular-tailwindcss-app-master/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/mypath/angular-tailwindcss-app-master/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/mypath/angular-tailwindcss-app-master/node_modules/postcss/lib/postcss.js:55:10)
    at Promise.resolve.then.then (/mypath/angular-tailwindcss-app-master/node_modules/postcss-loader/src/index.js:140:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jneterer** [comment]
@MatthewLHolden I have finally had time to update my tutorial. Take a look when you have a chance, it should fix the issues you are seeing! https://jacobneterer.medium.com/angular-and-tailwindcss-2388fb6e0bab
